dist: trusty
sudo: required
language: c
cache:
  apt: true
  directories:
  - $HOME/.opam

addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - aspcud
    - gcc-multilib

env:
  global:
  - NJOBS=2
  # system is == 4.02.3
  - COMPILER="system"
  - CAMLP5_VER="6.14"
  - FINDLIB_VER="1.4.1"
  - NATIVE_COMP="yes"
  - COQ_VER="8.6"

install:
- opam init -j ${NJOBS} --switch=${COMPILER} -n -y
- eval $(opam config env)
- opam config list
- opam install -j ${NJOBS} -y camlp5.${CAMLP5_VER} ocamlfind.${FINDLIB_VER} coq.${COQ_VER}
- opam list

script:
 - coq_makefile -f _CoqProject -o Makefile && make all examples
 - cd test-suite && coq_makefile -f _CoqProject -o Makefile && make

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/89ac14267a6cde573d95
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
